config/routes.rb
Rails.application.routes.draw do
  root 'game#index'
  resources :game, only: [:index]
  put '/game', to: 'game#update', as: :game
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/game_controller.rb
class GameController < ApplicationController
  before_action :set_game
  before_action :set_current_game, only: :update
  rescue_from StandardError, with: :error_game

  def index
  end

  def update
    service = GameCommandService.new(@game, place_params)
    service.execute

    render 'index'
  end

  private

  def set_game
    @game = RobotToyJonhnes::Game.new
  end

  def set_current_game
    @game.position_line = params[:current_line].to_i
    @game.position_column = params[:current_column].to_i
    @game.facing = params[:current_orientation].to_sym
  end

  def place_params
    params.permit(:command, :place)
  end

  def error_game(error)
    @error = error.message
    render 'index'
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/game_helper.rb
module GameHelper
  def game_commands_options
    { 'Place': '1', 'Move': '2', 'Left': '3', 'Right': '4' }
  end

  def robot_place?(game, line, column)
    same_line = game.position_line == line
    same_column = game.position_column == column
    same_line && same_column
  end
end

app/views/game/index.html.erb
<div>
  <h1>Robot Toy</h1>
  <% if @error %>
    <h3><%= @error %></h3>
  <% end %>
  <table>
    <% @game.board_width.times do |line_index| %>
      <tr>
        <% @game.board_height.times do |column_index| %>
          <td>
            <%= image_tag('direction.png', class: @game.facing.to_s.downcase) if robot_place? @game, line_index, column_index %>
          </td>
        <% end %>
      </tr>
    <% end %>
  </table>
  <div>
    <%= form_tag game_path, method: :put do %>
      <%= hidden_field_tag :current_line, @game.position_line %>
      <%= hidden_field_tag :current_column, @game.position_column %>
      <%= hidden_field_tag :current_orientation, @game.facing %>
      <%= select_tag :command, options_for_select(game_commands_options), onchange: 'changeCommandSelect(this)' %>
      <%= text_field_tag :place %>
      <button id="">GO!</button>
    <% end %>
  </div>
</div>

<script>
  function changeCommandSelect(element) {
    const place_field = document.getElementById('place');
    if(element.value === '1')
      place_field.style.display = 'inline-block';
    else
      place_field.style.display = 'none';
  }
</script>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>RobotToyWeb</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>